server.port: 8500
spring.data.elasticsearch.cluster-nodes: 127.0.0.1:9300
spring.data.elasticsearch.cluster-name: my-application



#spring:
#  redis:
#    host: 127.0.0.1 # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
#    timeout: 1000ms # 连接超时时间
